### ISSUE TITLE
Rename repo to dotfiles

### ISSUE THREAD

**Issue by cs-shadow** [tejasshah93/dotfiles#1]
`dotfiles` seems to be the web standard for such repositories so I suggest renaming it to that.

PS: I have nothing better to do at the moment other than stalking people on Github.

**Comment by tejasshah93** [comment]
I will. Infact I didn't :D Matthews had to clone the vim thing to his PC. So basically he did all the stuff 
#ToDo soon

**Comment by tejasshah93** [comment]
Done :P
